#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy version 2.8 load-balancer

apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt install update
apt-get install -y haproxy=2.8.\*
service haproxy start
sed -i '/errorfile 504/a listen thelaura' /etc/haproxy/haproxy.cfg
sed -i '/listen http-in/a         bind :80' /etc/haproxy/haproxy.cfg
sed -i '/bind :80/a         mode http' /etc/haproxy/haproxy.cfg
sed -i '/mode http/a         server 255406-web-01 18.204.13.187:80 check' /etc/haproxy/haproxy.cfg
sed -i '/server 255406-web-01 18.204.13.187:80 check/a         server 255406-web-02 100.26.224.74:80 check' /etc/haproxy/haproxy.cfg
sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy
service haproxy restart
