#!/usr/bin/env bash
# This script displays Best School 10 times but for the 9th iteration
# it displays Best School and then prints Hi using the while loop

i="0"
while [ $i -lt 10 ]
do
	echo "Best School"
	if [[ $i == 8 ]]
	then
		echo "Hi"
	fi
	((i=i+1));
done;
