#!/usr/bin/env bash
# This script loops from 1-10 and displays bad luck for the 4th iteration
# displays good luck for the 8th iteration and Best School for the
# remaining iterations using the while loop.

i="0"

while [ $i -lt 10 ]
do
	if [[ $i == 3 ]]
	then
		echo "bad luck"
	elif [[ $i == 7 ]]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i=i+1))
done;
