#!/usr/bin/env bash
# configure a ufw to deny all incoming traffic except on ports 22, 80 and 443

sudo apt-get install ufw
sudo ufw disable
sudo service ufw stop
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
sudo service ufw start

